@base_address = http://localhost:3000/api/people

POST {{base_address}}
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Negi",
    "age": 20
}

###
GET {{base_address}}

###
GET {{base_address}}/3

###
PUT {{base_address}}/3
Content-Type: application/json

{
    "id": 3,
    "firstName": "Mike",
    "lastName": "Smith",
    "age": 21
}

###
DELETE  {{base_address}}/4